openapi: 3.0.3
info:
  title: Application request manager
  description: An service for managing the applicaton request workflow
  version: 0.0.1

paths:
  /api/applications:
    post:
      operationId: CreateApplication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateApplicationRequest'
      responses:
        '201':
          description: 'Application created'
          headers:
            Location:
              schema:
                type: string
                format: uri
  /api/applications/{id}:
    get:
      operationId: RetrieveApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Stored application data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationResponse'
    delete:
      summary: Delete Application
      operationId: deleteApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteApplicationRequest'
      responses:
        '204':
          description: Application deleted
  /api/applications/{id}/reject:
    post:
      operationId: RejectApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RejectApplicationRequest'
      responses:
        '204':
          description: Application rejected
  /api/applications/{id}/verify:
    post:
      operationId: VerifyApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Application verified
  /api/applications/{id}/accept:
    post:
      operationId: AcceptApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Application accepted
  /api/applications/{id}/publish:
    post:
      operationId: PublishApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Application published
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublishingResponse'

components:
  schemas:
    CreateApplicationRequest:
      type: object
      required: 
        - name
        - body
      properties:
        name: 
          type: string
          pattern: '.*\S.*'
        body: 
          type: string
          pattern: '.*\S.*'
    DeleteApplicationRequest:
      type: object
      required: 
        - reason
      properties:
        reason: 
          type: string
          pattern: '.*\S.*'
    RejectApplicationRequest:
      type: object
      required: 
        - reason
      properties:
        reason: 
          type: string
          pattern: '.*\S.*'
    ApplicationRequest:
      type: object
      required: 
        - name
        - body
      properties:
        name: 
          type: string
          pattern: '.*\S.*'
        body: 
          type: string
          pattern: '.*\S.*'
    ApplicationState:
      type: string
      enum: [CREATED, DELETED, ACCEPTED, REJECTED, VERIFIED]
    ApplicationResponse:
      type: object
      required:
        - id
        - state
        - name
        - body
        - createdAt
      properties:
        id:
          type: string
          format: uuid
        state:
          $ref: '#/components/schemas/ApplicationState'
        name:
          type: string
        body:
          type: string
        createdAt:
          type: string
          format: date-time
    PublishingResponse:
      type: object
      required:
        - publishingId
      properties:
        publishingId:
          type: integer
          format: int64

